= SETUP

== Libraries

[cols="1,1,1"]
|===
| NAME
| LINK
| REFS

| react native paper
| https://callstack.github.io/react-native-paper/docs/guides/getting-started[open]


|===

UI:
[react native paper](https://callstack.github.io/react-native-paper/docs/guides/getting-started)
yarn add react-native-paper
yarn add react-native-safe-area-context
yarn add react-native-vector-icons 
- The library has specified dedicated steps for each platform. Please follow their [installation guide](https://github.com/oblador/react-native-vector-icons#installation) in order to properly use icon fonts.

Navigation:
[react navigation](https://reactnavigation.org/docs/getting-started/)
yarn add @react-navigation/native
yarn add react-native-screens react-native-safe-area-context
// yarn add @react-navigation/native-stack

https://reactnavigation.org/docs/stack-navigator
yarn add @react-navigation/stack
yarn add react-native-gesture-handler

State Management:
[mobx](https://mobx.js.org/installation.html)
yarn add mobx
yarn add mobx-react
mobx-plugin
https://github.com/mobxjs/mobx/blob/main/packages/eslint-plugin-mobx/README.md



[axios](https://axios-http.com/docs/intro)
yarn add axios

Local Storage:
[mmkv](https://github.com/mrousavy/react-native-mmkv)
yarn add react-native-mmkv

Notification:
yarn add @notifee/react-native [🔗](https://notifee.app/react-native/docs/installation)

Form:
yarn add formik 
(https://formik.org/docs/guides/react-native)
yarn add yup 
[🔗](https://github.com/jquense/yup)

[]
yarn add react-native-send-intent


yarn add @shopify/flash-list


fonts:
https://fonts.google.com/specimen/Poppins
https://medium.com/@prathiba2796/how-to-add-and-use-custom-fonts-in-react-native-369d5bba9203
https://callstack.github.io/react-native-paper/docs/guides/fonts/#installing-custom-fonts



path alias
https://javascript.plainenglish.io/react-native-path-aliasing-with-simplify-your-imports-and-enhance-your-codebase-9897efee96a8#:~:text=Setting%20Up%20Path%20Aliasing%20in,Edit%20your%20tsconfig.
yarn add --dev babel-plugin-module-resolver
custom path alias => @/*


for audio file / fetching apk from server
yarn add react-native-fs

yarn add react-native-android-intent-launcher



https://notifee.app/react-native/docs/android/behaviour#full-screen
https://notifee.app/react-native/docs/android/appearance#text-styling


yarn add uri-scheme
yarn uri-scheme add dhwajdialer --android
https://reactnavigation.org/docs/deep-linking/
https://reactnavigation.org/docs/deep-linking/#setup-on-android

testing
npx uri-scheme open [your deep link] --[ios|android]

adb shell am start -W -a android.intent.action.VIEW -d [your deep link] [your android package name]
adb shell am start -W -a android.intent.action.VIEW -d dhwajdialer com.dialer




https://thoughtbot.com/blog/implementing-deep-linking-in-react-native-a-quick-step-by-step-guide

full screen notification
https://notifee.app/react-native/docs/android/behaviour#full-screen


yarn add @isudaji/react-native-install-apk